<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6c5059f5-f3d3-4740-9033-9cba81e1a10e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FhirDiff.Ai\FhirDiff.Ai.csproj" />
    <ProjectReference Include="..\FhirDiff.Core\FhirDiff.Core.csproj" />
  </ItemGroup>

</Project>
